[2023-07-16 18:29:35,948] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-17T00:00:00+00:00 [queued]>
[2023-07-16 18:29:35,999] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-17T00:00:00+00:00 [queued]>
[2023-07-16 18:29:36,000] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:29:36,001] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-16 18:29:36,002] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:29:36,064] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): primer_task> on 2022-08-17 00:00:00+00:00
[2023-07-16 18:29:36,099] {standard_task_runner.py:52} INFO - Started process 544 to run task
[2023-07-16 18:29:36,118] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag', 'primer_task', 'scheduled__2022-08-17T00:00:00+00:00', '--job-id', '784', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmpcsek8666', '--error-file', '/tmp/tmpig7dztzp']
[2023-07-16 18:29:36,121] {standard_task_runner.py:80} INFO - Job 784: Subtask primer_task
[2023-07-16 18:29:36,518] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-17T00:00:00+00:00 [running]> on host fbcee05e3d0f
[2023-07-16 18:29:36,826] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag
AIRFLOW_CTX_TASK_ID=primer_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-17T00:00:00+00:00
[2023-07-16 18:29:36,832] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-16 18:29:36,833] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'que carajos mundo, esta es nuestra primera tarea usando bash operator!']
[2023-07-16 18:29:36,864] {subprocess.py:85} INFO - Output:
[2023-07-16 18:29:36,868] {subprocess.py:92} INFO - bash: line 1: que: command not found
[2023-07-16 18:29:36,869] {subprocess.py:96} INFO - Command exited with return code 127
[2023-07-16 18:29:36,932] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-16 18:29:36,952] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag, task_id=primer_task, execution_date=20220817T000000, start_date=20230716T182935, end_date=20230716T182936
[2023-07-16 18:29:37,001] {standard_task_runner.py:97} ERROR - Failed to execute job 784 for task primer_task (Bash command failed. The command returned a non-zero exit code 127.; 544)
[2023-07-16 18:29:37,038] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-16 18:29:37,255] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
