[2023-07-16 18:38:01,746] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-07T00:00:00+00:00 [queued]>
[2023-07-16 18:38:01,786] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-07T00:00:00+00:00 [queued]>
[2023-07-16 18:38:01,787] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:38:01,788] {taskinstance.py:1377} INFO - Starting attempt 5 of 6
[2023-07-16 18:38:01,789] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:38:01,833] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): primer_task> on 2022-08-07 00:00:00+00:00
[2023-07-16 18:38:01,839] {standard_task_runner.py:52} INFO - Started process 543 to run task
[2023-07-16 18:38:01,915] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag', 'primer_task', 'scheduled__2022-08-07T00:00:00+00:00', '--job-id', '1132', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag.py', '--cfg-path', '/tmp/tmpnw4uvhc8', '--error-file', '/tmp/tmpnnimoj4_']
[2023-07-16 18:38:01,927] {standard_task_runner.py:80} INFO - Job 1132: Subtask primer_task
[2023-07-16 18:38:02,207] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-07T00:00:00+00:00 [running]> on host fbcee05e3d0f
[2023-07-16 18:38:02,559] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag
AIRFLOW_CTX_TASK_ID=primer_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-07T00:00:00+00:00
[2023-07-16 18:38:02,564] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-16 18:38:02,577] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'que carajos mundo, esta es nuestra primera tarea usando bash operator!']
[2023-07-16 18:38:02,622] {subprocess.py:85} INFO - Output:
[2023-07-16 18:38:02,625] {subprocess.py:92} INFO - bash: line 1: que: command not found
[2023-07-16 18:38:02,644] {subprocess.py:96} INFO - Command exited with return code 127
[2023-07-16 18:38:02,770] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-16 18:38:02,780] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag, task_id=primer_task, execution_date=20220807T000000, start_date=20230716T183801, end_date=20230716T183802
[2023-07-16 18:38:02,819] {standard_task_runner.py:97} ERROR - Failed to execute job 1132 for task primer_task (Bash command failed. The command returned a non-zero exit code 127.; 543)
[2023-07-16 18:38:02,860] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-16 18:38:03,004] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
