[2023-07-16 18:47:18,212] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-20T00:00:00+00:00 [queued]>
[2023-07-16 18:47:18,239] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-20T00:00:00+00:00 [queued]>
[2023-07-16 18:47:18,240] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:47:18,240] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2023-07-16 18:47:18,242] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:47:18,303] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): primer_task> on 2022-08-20 00:00:00+00:00
[2023-07-16 18:47:18,312] {standard_task_runner.py:52} INFO - Started process 1134 to run task
[2023-07-16 18:47:18,322] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag', 'primer_task', 'scheduled__2022-08-20T00:00:00+00:00', '--job-id', '1402', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmpn9lcud74', '--error-file', '/tmp/tmp976ejt7s']
[2023-07-16 18:47:18,324] {standard_task_runner.py:80} INFO - Job 1402: Subtask primer_task
[2023-07-16 18:47:18,551] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-20T00:00:00+00:00 [running]> on host fbcee05e3d0f
[2023-07-16 18:47:18,790] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag
AIRFLOW_CTX_TASK_ID=primer_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-20T00:00:00+00:00
[2023-07-16 18:47:18,792] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-16 18:47:18,794] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'que carajos mundo, esta es nuestra primera tarea usando bash operator!']
[2023-07-16 18:47:18,814] {subprocess.py:85} INFO - Output:
[2023-07-16 18:47:18,817] {subprocess.py:92} INFO - bash: line 1: que: command not found
[2023-07-16 18:47:18,818] {subprocess.py:96} INFO - Command exited with return code 127
[2023-07-16 18:47:18,850] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-16 18:47:18,858] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag, task_id=primer_task, execution_date=20220820T000000, start_date=20230716T184718, end_date=20230716T184718
[2023-07-16 18:47:18,895] {standard_task_runner.py:97} ERROR - Failed to execute job 1402 for task primer_task (Bash command failed. The command returned a non-zero exit code 127.; 1134)
[2023-07-16 18:47:18,947] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-16 18:47:19,041] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
