[2023-07-16 18:38:01,492] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-10T00:00:00+00:00 [queued]>
[2023-07-16 18:38:01,513] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-10T00:00:00+00:00 [queued]>
[2023-07-16 18:38:01,514] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:38:01,514] {taskinstance.py:1377} INFO - Starting attempt 5 of 6
[2023-07-16 18:38:01,515] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:38:01,548] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): primer_task> on 2022-08-10 00:00:00+00:00
[2023-07-16 18:38:01,563] {standard_task_runner.py:52} INFO - Started process 534 to run task
[2023-07-16 18:38:01,572] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag', 'primer_task', 'scheduled__2022-08-10T00:00:00+00:00', '--job-id', '1124', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag.py', '--cfg-path', '/tmp/tmpzwe9j10h', '--error-file', '/tmp/tmpa5vhekwk']
[2023-07-16 18:38:01,574] {standard_task_runner.py:80} INFO - Job 1124: Subtask primer_task
[2023-07-16 18:38:01,706] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-10T00:00:00+00:00 [running]> on host fbcee05e3d0f
[2023-07-16 18:38:01,910] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag
AIRFLOW_CTX_TASK_ID=primer_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-10T00:00:00+00:00
[2023-07-16 18:38:01,919] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-16 18:38:01,930] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'que carajos mundo, esta es nuestra primera tarea usando bash operator!']
[2023-07-16 18:38:01,966] {subprocess.py:85} INFO - Output:
[2023-07-16 18:38:01,969] {subprocess.py:92} INFO - bash: line 1: que: command not found
[2023-07-16 18:38:01,970] {subprocess.py:96} INFO - Command exited with return code 127
[2023-07-16 18:38:02,332] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-16 18:38:02,340] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag, task_id=primer_task, execution_date=20220810T000000, start_date=20230716T183801, end_date=20230716T183802
[2023-07-16 18:38:02,423] {standard_task_runner.py:97} ERROR - Failed to execute job 1124 for task primer_task (Bash command failed. The command returned a non-zero exit code 127.; 534)
[2023-07-16 18:38:02,471] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-16 18:38:02,585] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
