[2023-07-16 18:35:57,398] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-03T00:00:00+00:00 [queued]>
[2023-07-16 18:35:57,467] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-03T00:00:00+00:00 [queued]>
[2023-07-16 18:35:57,475] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:35:57,477] {taskinstance.py:1377} INFO - Starting attempt 4 of 6
[2023-07-16 18:35:57,503] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:35:57,680] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): primer_task> on 2022-08-03 00:00:00+00:00
[2023-07-16 18:35:57,740] {standard_task_runner.py:52} INFO - Started process 379 to run task
[2023-07-16 18:35:57,767] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag', 'primer_task', 'scheduled__2022-08-03T00:00:00+00:00', '--job-id', '1112', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag.py', '--cfg-path', '/tmp/tmpd3jppi_v', '--error-file', '/tmp/tmpg_or3nly']
[2023-07-16 18:35:57,785] {standard_task_runner.py:80} INFO - Job 1112: Subtask primer_task
[2023-07-16 18:35:58,314] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-03T00:00:00+00:00 [running]> on host fbcee05e3d0f
[2023-07-16 18:35:59,408] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag
AIRFLOW_CTX_TASK_ID=primer_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-03T00:00:00+00:00
[2023-07-16 18:35:59,423] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-16 18:35:59,439] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'que carajos mundo, esta es nuestra primera tarea usando bash operator!']
[2023-07-16 18:35:59,495] {subprocess.py:85} INFO - Output:
[2023-07-16 18:35:59,497] {subprocess.py:92} INFO - bash: line 1: que: command not found
[2023-07-16 18:35:59,498] {subprocess.py:96} INFO - Command exited with return code 127
[2023-07-16 18:35:59,690] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-16 18:35:59,874] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag, task_id=primer_task, execution_date=20220803T000000, start_date=20230716T183557, end_date=20230716T183559
[2023-07-16 18:36:00,200] {standard_task_runner.py:97} ERROR - Failed to execute job 1112 for task primer_task (Bash command failed. The command returned a non-zero exit code 127.; 379)
[2023-07-16 18:36:00,409] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-16 18:36:00,707] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
