[2023-07-16 18:29:26,604] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-11T00:00:00+00:00 [queued]>
[2023-07-16 18:29:26,914] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-11T00:00:00+00:00 [queued]>
[2023-07-16 18:29:26,962] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:29:26,995] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-16 18:29:27,008] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:29:27,164] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): primer_task> on 2022-08-11 00:00:00+00:00
[2023-07-16 18:29:27,186] {standard_task_runner.py:52} INFO - Started process 459 to run task
[2023-07-16 18:29:27,237] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag', 'primer_task', 'scheduled__2022-08-11T00:00:00+00:00', '--job-id', '754', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmpzxcywqs8', '--error-file', '/tmp/tmpprnt_av0']
[2023-07-16 18:29:27,259] {standard_task_runner.py:80} INFO - Job 754: Subtask primer_task
[2023-07-16 18:29:27,961] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-11T00:00:00+00:00 [running]> on host fbcee05e3d0f
[2023-07-16 18:29:28,548] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag
AIRFLOW_CTX_TASK_ID=primer_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-11T00:00:00+00:00
[2023-07-16 18:29:28,593] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-16 18:29:28,615] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'que carajos mundo, esta es nuestra primera tarea usando bash operator!']
[2023-07-16 18:29:28,727] {subprocess.py:85} INFO - Output:
[2023-07-16 18:29:28,743] {subprocess.py:92} INFO - bash: line 1: que: command not found
[2023-07-16 18:29:28,752] {subprocess.py:96} INFO - Command exited with return code 127
[2023-07-16 18:29:28,869] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-16 18:29:28,918] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag, task_id=primer_task, execution_date=20220811T000000, start_date=20230716T182926, end_date=20230716T182928
[2023-07-16 18:29:29,062] {standard_task_runner.py:97} ERROR - Failed to execute job 754 for task primer_task (Bash command failed. The command returned a non-zero exit code 127.; 459)
[2023-07-16 18:29:29,116] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-16 18:29:29,365] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
