[2023-07-16 18:31:30,401] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-11T00:00:00+00:00 [queued]>
[2023-07-16 18:31:30,416] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-11T00:00:00+00:00 [queued]>
[2023-07-16 18:31:30,416] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:31:30,417] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-07-16 18:31:30,418] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:31:30,441] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): primer_task> on 2022-08-11 00:00:00+00:00
[2023-07-16 18:31:30,445] {standard_task_runner.py:52} INFO - Started process 1419 to run task
[2023-07-16 18:31:30,450] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag', 'primer_task', 'scheduled__2022-08-11T00:00:00+00:00', '--job-id', '1038', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmpzae1z7nh', '--error-file', '/tmp/tmpq_kzjbnq']
[2023-07-16 18:31:30,451] {standard_task_runner.py:80} INFO - Job 1038: Subtask primer_task
[2023-07-16 18:31:30,536] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-11T00:00:00+00:00 [running]> on host fbcee05e3d0f
[2023-07-16 18:31:30,642] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag
AIRFLOW_CTX_TASK_ID=primer_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-11T00:00:00+00:00
[2023-07-16 18:31:30,644] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-16 18:31:30,645] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'que carajos mundo, esta es nuestra primera tarea usando bash operator!']
[2023-07-16 18:31:30,655] {subprocess.py:85} INFO - Output:
[2023-07-16 18:31:30,657] {subprocess.py:92} INFO - bash: line 1: que: command not found
[2023-07-16 18:31:30,658] {subprocess.py:96} INFO - Command exited with return code 127
[2023-07-16 18:31:30,677] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-16 18:31:30,683] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag, task_id=primer_task, execution_date=20220811T000000, start_date=20230716T183130, end_date=20230716T183130
[2023-07-16 18:31:30,699] {standard_task_runner.py:97} ERROR - Failed to execute job 1038 for task primer_task (Bash command failed. The command returned a non-zero exit code 127.; 1419)
[2023-07-16 18:31:30,742] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-16 18:31:30,792] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
