[2023-07-16 18:35:57,370] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-02T00:00:00+00:00 [queued]>
[2023-07-16 18:35:57,505] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-02T00:00:00+00:00 [queued]>
[2023-07-16 18:35:57,510] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:35:57,511] {taskinstance.py:1377} INFO - Starting attempt 4 of 6
[2023-07-16 18:35:57,512] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 18:35:57,615] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): primer_task> on 2022-08-02 00:00:00+00:00
[2023-07-16 18:35:57,625] {standard_task_runner.py:52} INFO - Started process 375 to run task
[2023-07-16 18:35:57,666] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag', 'primer_task', 'scheduled__2022-08-02T00:00:00+00:00', '--job-id', '1113', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag.py', '--cfg-path', '/tmp/tmpa1_8zcy9', '--error-file', '/tmp/tmp_cz9018s']
[2023-07-16 18:35:57,676] {standard_task_runner.py:80} INFO - Job 1113: Subtask primer_task
[2023-07-16 18:35:58,110] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag.primer_task scheduled__2022-08-02T00:00:00+00:00 [running]> on host fbcee05e3d0f
[2023-07-16 18:35:58,870] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag
AIRFLOW_CTX_TASK_ID=primer_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-02T00:00:00+00:00
[2023-07-16 18:35:58,923] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-16 18:35:58,947] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'que carajos mundo, esta es nuestra primera tarea usando bash operator!']
[2023-07-16 18:35:59,102] {subprocess.py:85} INFO - Output:
[2023-07-16 18:35:59,156] {subprocess.py:92} INFO - bash: line 1: que: command not found
[2023-07-16 18:35:59,171] {subprocess.py:96} INFO - Command exited with return code 127
[2023-07-16 18:35:59,468] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-16 18:35:59,926] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag, task_id=primer_task, execution_date=20220802T000000, start_date=20230716T183557, end_date=20230716T183559
[2023-07-16 18:36:00,330] {standard_task_runner.py:97} ERROR - Failed to execute job 1113 for task primer_task (Bash command failed. The command returned a non-zero exit code 127.; 375)
[2023-07-16 18:36:00,486] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-16 18:36:00,885] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
